version: "3.7"

services:
  postgres:
    image: postgres:12.3
    container_name: markono-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Markono1!
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - markono-network

volumes:
  pgdata:

networks:
  markono-network:
    name: markono-network
