version: "3.7"

services:
  postgres:
    image: postgres:12.2
    container_name: markono-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Markono1!
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - markono-network

volumes:
  dbdata:
  
networks:
  markono-network:
    name: markono-network
