version: "3.7"

services:
  # mysql:
  #   image: mysql:5.6
  #   container_name: markono-mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_DATABASE: employees
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: Markono1!
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #     - ./db/mysql/mysql-employees.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - markono-network

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   container_name: markono-mssql
  #   # command: /bin/bash ./entrypoint.sh
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_PID=Express
  #     - SA_PASSWORD=Markono1!
  #   # volumes:
  #   #   - dbdata:/var/opt/mssql/data
  #   #   - ./db/mssql/docker-entrypoint.sh:/entrypoint.sh
  #   #   - ./db/mssql/docker-db-init.sh:/db-init.sh
  #   #   - ./db/mssql/mssql-cars.sql:/db-init.sql
  #   networks:
  #     - markono-network
  
  postgres:
    image: postgres:12.2
    container_name: markono-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Markono1!
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - markono-network

volumes:
  dbdata:
  
networks:
  markono-network:
    name: markono-network
